name: Terraform Deploy to Alibaba Cloud for Production environment

on:
  push:
    branches:
      - main
    paths:
      - 'environments/production/**.tf'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      ALICLOUD_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      ALICLOUD_SECRET_KEY: ${{ secrets.SECRET_KEY }}

    defaults:
      run:
        working-directory: environments/staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
